name: build

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -A x64

      - name: Build
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: potatoclient
          path: |
            build/Release/client.dll
            build/Release/client.pdb
            build/Release/injector.exe
